deployment:
  tasks:
    - export DEPLOYPATH=/home/n9rvfnj0euew/public_html
    - /bin/mv $DEPLOYPATH /home/n9rvfnj0euew/archive/public_html_$(date +'%Y%m%d%H%M%S')
    - /bin/mkdir $DEPLOYPATH
    - /bin/cp -r * $DEPLOYPATH